changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot[bot]
  categories:
    - title: Updates
      labels:
        - '*'
      exclude:
        labels:
          - dependencies